# Generated by Django 3.1.7 on 2021-05-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210504_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='summary',
            new_name='synopsis',
        ),
    ]
