# Generated by Django 3.1.7 on 2021-05-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210504_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(help_text='Enter a brief description of the anime', max_length=2000),
        ),
    ]
