# Generated by Django 3.1.7 on 2021-05-04 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210504_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['year', 'season']},
        ),
    ]
