# Generated by Django 3.1.7 on 2021-05-04 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210504_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['name']},
        ),
    ]
