# Generated by Django 3.1.7 on 2021-05-08 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210504_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={},
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='starting_air_date',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.AddField(
            model_name='anime',
            name='airing_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='image_url',
            field=models.URLField(default='http://www.google.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='members',
            field=models.BigIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.CharField(choices=[('M', 'Manga'), ('A', 'Anime'), ('LN', 'Light Novel'), ('WM', 'Web Manga'), ('O', 'Original')], default='A', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='studios',
            field=models.ManyToManyField(to='catalog.Studio'),
        ),
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.CharField(choices=[('TV', 'TV'), ('OVA', 'OVA'), ('Mov', 'Movie'), ('Sp', 'Special'), ('ONA', 'ONA'), ('Mus', 'Music')], default='TV', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(help_text='Enter a brief description of the anime', max_length=5000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('Win', 'Winter'), ('Spr', 'Spring'), ('Sum', 'Summer'), ('Aut', 'Autumn')], max_length=3),
        ),
    ]
