# Generated by Django 3.1.7 on 2021-05-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210508_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
