# Generated by Django 3.1.7 on 2021-05-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20210508_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(choices=[('Win', 'Winter'), ('Spr', 'Spring'), ('Sum', 'Summer'), ('Fal', 'Fall')], max_length=3),
        ),
    ]
