# Generated by Django 3.1.7 on 2021-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210508_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
