# Generated by Django 3.1.7 on 2021-05-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210509_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title_english',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
