# Generated by Django 3.1.7 on 2021-05-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210509_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='source',
            field=models.TextField(verbose_name=50),
        ),
    ]
