# Generated by Django 3.1.7 on 2021-05-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20210509_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='mal_id',
        ),
    ]
