# Generated by Django 3.1.7 on 2021-05-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20210509_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='scored_by',
            field=models.IntegerField(null=True),
        ),
    ]
