# Generated by Django 3.1.7 on 2021-05-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210509_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year']},
        ),
    ]
