# Generated by Django 3.1.7 on 2021-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20210509_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='scored_by',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='title_english',
        ),
        migrations.AlterField(
            model_name='anime',
            name='type',
            field=models.TextField(max_length=50),
        ),
    ]
