# Generated by Django 3.1.7 on 2021-05-11 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
    ]
