# Generated by Django 3.1.7 on 2021-08-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20210804_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='streaming_websites',
            field=models.ManyToManyField(blank=True, to='catalog.StreamingWebsite'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='catalog.Anime'),
        ),
    ]
