# Generated by Django 3.1.7 on 2021-08-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_auto_20210804_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='latest_ep_url',
            field=models.URLField(blank=True),
        ),
    ]
