# Generated by Django 3.1.7 on 2021-09-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_anime_latest_ep_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamingwebsite',
            name='new_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
