# Generated by Django 3.1.7 on 2021-09-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_streamingwebsite_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingwebsite',
            name='new_field',
        ),
    ]
